/root/.venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:318: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
INFO:     Started server process [1865]
INFO:     Waiting for application startup.
Connected to MongoDB: telegram_marketplace
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8001): address already in use
INFO:     Waiting for application shutdown.
Disconnected from MongoDB
INFO:     Application shutdown complete.
